---
- name: Kubernetes Master

  hosts: master
  remote_user: pirate
  become: true

  vars:
    dns:
      service_ip: 10.200.100.10
      domain: cluster.local

  roles:
  - etcd
  - role: flannel
    mode: master
  - docker
  - role: kubernetes
    mode: master

- name: Kubernetes Nodes

  hosts: nodes
  remote_user: pirate
  become: true

  roles:
  - role: flannel
    mode: node
  - docker
  - role: kubernetes
    mode: node
